.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GZSIZE" "1" "September 2019" "" "GZSize Manual"
.
.SH "NAME"
\fBgzsize\fR \- Get the uncompressed size of an archive
.
.SH "SYNOPSIS"
\fBgzsize\fR \fIfile\fR [\fIfile\fR \.\.\.]
.
.SH "DESCRIPTION"
Print the uncompressed size of a GZipped file\. If multiple files are given, print the total size of all of them\. \fB\-\fR reads on stdin\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR
Print the help and exit\.
.
.TP
\fB\-H\fR
Output a human\-readable size, like "263M"\.
.
.TP
\fB\-v\fR
Print the version and exit\.
.
.SH "EXAMPLES"
.
.TP
Get the uncompressed size of a file
\fBgzsize myfile\.gz\fR
.
.TP
Get the uncompressed size of stdin
\fBcurl https://example\.com/somefile\.gz | gzsize \-\fR
.
.SH "AUTHOR"
Written by Baptiste Fontaine <\fIb@ptistefontaine\.fr\fR>\.
.
.SH "BUGS"
Bugs should be reported at \fIhttps://github\.com/bfontaine/gzsize/issues\fR\.
.
.SH "SEE ALSO"
The project homepage is at \fIhttps://github\.com/bfontaine/gzsize\fR\.
